#zf220122.2117
# sources: https://hub.docker.com/r/marcel1691/thingspeak

version: "3.9"

services:
  thingspeak:
  #docker run --name thingspeak -p 80:3000 -d marcel1691/thingspeak
    container_name: thingspeak
    restart: unless-stopped
    image: marcel1691/thingspeak
    ports:
      - '8080:3000'
