#zf220122.1541
# sources: https://hub.docker.com/r/synomi/thingspeak

version: "3.9"

services:
  mysql55:
  #docker run --name mysql55 -e MYSQL_ROOT_PASSWORD=speak -d mysql:5.5
    container_name: mysql55
    restart: unless-stopped
    image: mysql:5.5
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=speak
#    volumes:
#      - /Users/robin/Data/pytorch-models:/modelstore/detection
#      - ./Data/pytorch-models:/modelstore/detection


  thingspeak:
  #docker run --name thingspeak -p 80:80 --link mysql55:mysql -d synomi/thingspeak
    container_name: thingspeak
    restart: unless-stopped
    image: synomi/thingspeak
    ports:
      - '8080:80'
    links:
      - "mysql55:mysql"
#    environment:
#      - VISION-DETECTION=True
#      - API-KEY=toto
#    volumes:
#      - /Users/robin/Data/pytorch-models:/modelstore/detection
#      - ./Data/pytorch-models:/modelstore/detection

